# Generated by Django 5.0.4 on 2024-04-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_customuser_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('guest', 'Guest')], default='guest'),
        ),
    ]
